import { MealItem, DayData, ScannedFoodComponent } from './types';

export const INITIAL_MEALS: MealItem[] = [
  {
    id: 'm1',
    slot: 'breakfast',
    slotName: 'Breakfast',
    time: '07:45',
    name: 'Poached eggs, rye crisps & avocado',
    description: '2 organic eggs, Finn crisp sourdough, half Haas avocado',
    calories: 450,
    protein: 24,
    carbs: 32,
    fat: 26,
    iconType: 'egg',
    logged: true,
  },
  {
    id: 'm2',
    slot: 'lunch',
    slotName: 'Lunch',
    time: '12:30',
    name: 'Arctic char, root greens & quinoa',
    description: 'Wild Arctic char fillet, steamed kale, tricolor quinoa',
    calories: 680,
    protein: 52,
    carbs: 64,
    fat: 16,
    iconType: 'bowl',
    logged: true,
  },
  {
    id: 'm3',
    slot: 'snack',
    slotName: 'Snack',
    time: '16:15',
    name: 'Skyr yogurt & lingonberries',
    description: 'Icelandic traditional skyr, wild Nordic lingonberry coulis',
    calories: 190,
    protein: 18,
    carbs: 22,
    fat: 3,
    iconType: 'berry',
    logged: true,
  },
  {
    id: 'm4',
    slot: 'dinner',
    slotName: 'Dinner',
    time: 'Evening slot',
    name: 'Not recorded yet',
    description: 'Awaiting dinner telemetry',
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    iconType: 'utensils',
    logged: false,
  },
];

export const INITIAL_DAYS: DayData[] = [
  {
    dayKey: 'M',
    dayShort: 'Mon',
    label: 'Monday',
    calories: 2100,
    displayKcal: '2.1k',
    hasData: true,
    protein: 135,
    carbs: 210,
    fat: 62,
    waterReached: true,
  },
  {
    dayKey: 'T',
    dayShort: 'Tue',
    label: 'Tuesday',
    calories: 1900,
    displayKcal: '1.9k',
    hasData: true,
    protein: 128,
    carbs: 195,
    fat: 58,
    waterReached: true,
  },
  {
    dayKey: 'W',
    dayShort: 'Wed',
    label: 'Wednesday',
    calories: 2200,
    displayKcal: '2.2k',
    hasData: true,
    protein: 142,
    carbs: 230,
    fat: 65,
    waterReached: true,
  },
  {
    dayKey: 'T',
    dayShort: 'Thu',
    label: 'Thursday',
    calories: 2000,
    displayKcal: '2.0k',
    hasData: true,
    protein: 130,
    carbs: 215,
    fat: 60,
    waterReached: true,
  },
  {
    dayKey: 'F',
    dayShort: 'Fri',
    label: 'Friday',
    calories: 1720,
    displayKcal: '1.7k',
    isToday: true,
    hasData: true,
    protein: 112,
    carbs: 180,
    fat: 45,
    waterReached: true,
  },
  {
    dayKey: 'S',
    dayShort: 'Sat',
    label: 'Saturday',
    calories: 0,
    displayKcal: '--',
    hasData: false,
    protein: 0,
    carbs: 0,
    fat: 0,
    waterReached: false,
  },
  {
    dayKey: 'S',
    dayShort: 'Sun',
    label: 'Sunday',
    calories: 0,
    displayKcal: '--',
    hasData: false,
    protein: 0,
    carbs: 0,
    fat: 0,
    waterReached: false,
  },
];

export const SCANNED_MEAL_PRESET: {
  name: string;
  image: string;
  components: ScannedFoodComponent[];
} = {
  name: 'Nordic Chicken & Quinoa Harvest Bowl',
  image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1000&q=80',
  components: [
    {
      id: 'c1',
      name: 'Grilled Chicken',
      confidence: 98,
      calories: 220,
      protein: 26,
      carbs: 0,
      fat: 5,
      icon: 'utensils',
    },
    {
      id: 'c2',
      name: 'Quinoa Bowl',
      confidence: 94,
      calories: 180,
      protein: 6,
      carbs: 32,
      fat: 3,
      icon: 'grain',
    },
    {
      id: 'c3',
      name: 'Fresh Avocado',
      confidence: 96,
      calories: 95,
      protein: 1,
      carbs: 4,
      fat: 9,
      icon: 'leaf',
    },
    {
      id: 'c4',
      name: 'Cherry Tomatoes & Greens',
      confidence: 97,
      calories: 40,
      protein: 1,
      carbs: 6,
      fat: 1,
      icon: 'sparkles',
    },
  ],
};

export const ALTERNATE_PRESETS = [
  {
    name: 'Norwegian Smoked Salmon & Sourdough',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=1000&q=80',
    components: [
      { id: 'a1', name: 'Norwegian Salmon', confidence: 99, calories: 240, protein: 28, carbs: 0, fat: 14, icon: 'fish' },
      { id: 'a2', name: 'Rye Sourdough', confidence: 96, calories: 160, protein: 5, carbs: 32, fat: 2, icon: 'bread' },
      { id: 'a3', name: 'Dill & Creme Fraiche', confidence: 92, calories: 75, protein: 2, carbs: 3, fat: 7, icon: 'leaf' },
    ],
  },
  {
    name: 'Arctic Berry & Protein Skyr',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1000&q=80',
    components: [
      { id: 'b1', name: 'Icelandic Skyr', confidence: 97, calories: 150, protein: 20, carbs: 8, fat: 0, icon: 'milk' },
      { id: 'b2', name: 'Wild Blueberries', confidence: 95, calories: 60, protein: 1, carbs: 14, fat: 0, icon: 'berry' },
      { id: 'b3', name: 'Granola & Flaxseed', confidence: 93, calories: 120, protein: 4, carbs: 18, fat: 5, icon: 'grain' },
    ],
  },
];
